language: node_js
node_js:
  - stable

dist: trusty

sudo: requiredbranches:
  only:
  - masterbefore_script:
  - npm install -g @angular/cliscript:
- ng build --prod --base-href https://github.com/layornos/DES_Compare_Editor 
