dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build
  - cd dist/angular-github-pages-travis
  - cp index.html 404.html
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN
  local_dir: dist/DESCompareEditor
  on:
    branch: master
