language: node_js
node_js:
  - stable

dist: trusty

sudo: requiredbranches:
  only:
  - masterbefore_script:
  - npm install -g @angular/cliscript:
- ng build --prod --base-href git+https://$TOKEN:x-oauth-basic@github.com/foo/bar.git
